// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package config

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockConfigLoader creates a new instance of MockConfigLoader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigLoader {
	mock := &MockConfigLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfigLoader is an autogenerated mock type for the ConfigLoader type
type MockConfigLoader struct {
	mock.Mock
}

type MockConfigLoader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigLoader) EXPECT() *MockConfigLoader_Expecter {
	return &MockConfigLoader_Expecter{mock: &_m.Mock}
}

// GetBool provides a mock function for the type MockConfigLoader
func (_mock *MockConfigLoader) GetBool(path []string, defaultValue bool) bool {
	ret := _mock.Called(path, defaultValue)

	if len(ret) == 0 {
		panic("no return value specified for GetBool")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func([]string, bool) bool); ok {
		r0 = returnFunc(path, defaultValue)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockConfigLoader_GetBool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBool'
type MockConfigLoader_GetBool_Call struct {
	*mock.Call
}

// GetBool is a helper method to define mock.On call
//   - path []string
//   - defaultValue bool
func (_e *MockConfigLoader_Expecter) GetBool(path any, defaultValue any) *MockConfigLoader_GetBool_Call {
	return &MockConfigLoader_GetBool_Call{Call: _e.mock.On("GetBool", path, defaultValue)}
}

func (_c *MockConfigLoader_GetBool_Call) Run(run func(path []string, defaultValue bool)) *MockConfigLoader_GetBool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConfigLoader_GetBool_Call) Return(b bool) *MockConfigLoader_GetBool_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockConfigLoader_GetBool_Call) RunAndReturn(run func(path []string, defaultValue bool) bool) *MockConfigLoader_GetBool_Call {
	_c.Call.Return(run)
	return _c
}

// GetInt provides a mock function for the type MockConfigLoader
func (_mock *MockConfigLoader) GetInt(path []string, defaultValue int) int {
	ret := _mock.Called(path, defaultValue)

	if len(ret) == 0 {
		panic("no return value specified for GetInt")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func([]string, int) int); ok {
		r0 = returnFunc(path, defaultValue)
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockConfigLoader_GetInt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInt'
type MockConfigLoader_GetInt_Call struct {
	*mock.Call
}

// GetInt is a helper method to define mock.On call
//   - path []string
//   - defaultValue int
func (_e *MockConfigLoader_Expecter) GetInt(path any, defaultValue any) *MockConfigLoader_GetInt_Call {
	return &MockConfigLoader_GetInt_Call{Call: _e.mock.On("GetInt", path, defaultValue)}
}

func (_c *MockConfigLoader_GetInt_Call) Run(run func(path []string, defaultValue int)) *MockConfigLoader_GetInt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConfigLoader_GetInt_Call) Return(n int) *MockConfigLoader_GetInt_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockConfigLoader_GetInt_Call) RunAndReturn(run func(path []string, defaultValue int) int) *MockConfigLoader_GetInt_Call {
	_c.Call.Return(run)
	return _c
}

// GetString provides a mock function for the type MockConfigLoader
func (_mock *MockConfigLoader) GetString(path []string, defaultValue string) string {
	ret := _mock.Called(path, defaultValue)

	if len(ret) == 0 {
		panic("no return value specified for GetString")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func([]string, string) string); ok {
		r0 = returnFunc(path, defaultValue)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfigLoader_GetString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetString'
type MockConfigLoader_GetString_Call struct {
	*mock.Call
}

// GetString is a helper method to define mock.On call
//   - path []string
//   - defaultValue string
func (_e *MockConfigLoader_Expecter) GetString(path any, defaultValue any) *MockConfigLoader_GetString_Call {
	return &MockConfigLoader_GetString_Call{Call: _e.mock.On("GetString", path, defaultValue)}
}

func (_c *MockConfigLoader_GetString_Call) Run(run func(path []string, defaultValue string)) *MockConfigLoader_GetString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConfigLoader_GetString_Call) Return(s string) *MockConfigLoader_GetString_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfigLoader_GetString_Call) RunAndReturn(run func(path []string, defaultValue string) string) *MockConfigLoader_GetString_Call {
	_c.Call.Return(run)
	return _c
}
